# Login Screen Widget
<LoginScreen>:
    # This is a grid layout with 1 column
    GridLayout:
        cols: 1
        # This is another grid layout with 1 column for the login form
        GridLayout:
            cols: 1
            Label:
                text: 'User Login'
            TextInput:
                id: username
                hint_text: 'Username'
            TextInput:
                id: password
                hint_text: 'Password'
            Button:
                text: 'Login'
                on_press: root.login(root.ids.username.text, root.ids.password.text)
            Label:
                id: login_wrong
                text: ''
        # This is another grid layout with 2 columns for additional options
        GridLayout:
            cols: 2
            Button:
                text: 'Forgot password?'
            Button:
                text: 'Sign up'
                on_press: root.sign_up()

# Sign Up Screen Widget
<SignUpScreen>:
    GridLayout:
        cols: 1
        Label:
            text: 'Sign up for space journey !'
        TextInput:
            id: username
            hint_text: 'Username'
        TextInput:
            id: password
            hint_text: 'Password'
        Button:
            text: 'Sign In'
            on_press: root.add_user(root.ids.username.text, root.ids.password.text)

# Sign Up Screen Success Widget
<SignUpScreenSuccess>:
    GridLayout:
        cols: 1
        Label:
            text: 'Sign up successful!'
        Button:
            text: 'Login page'
            on_press: root.go_to_login()

# Login Screen Success Widget
<LoginScreenSuccess>:
    GridLayout:
        cols: 1
        Button:
            text: 'Logout'
            on_press: root.log_out()
        Label:
            text: 'How do you feel ?'
        TextInput:
            id: feeling
            hint_text: 'Things to try: happy, sad, unloved...'
        Button:
            text: 'Enlighten me'
            on_press: root.get_quote(root.ids.feeling.text)
        Label:
            id: quote
            text: ''

# Root Widget that contains all other widgets
<RootWidged>:
    LoginScreen:
        name: 'login_screen'
    SignUpScreen:
        name: 'sign_up_screen'
    SignUpScreenSuccess:
        name: 'sign_up_screen_success'
    LoginScreenSuccess:
        name: 'login_screen_success'